// REDUX ACTION TYPES

export const OPEN__DETAIL__COMMON = 'OPEN__DETAIL__COMMON'
 export const CLOSE__DETAIL__COMMON = 'CLOSE__DETAIL__COMMON'

 export const OPEN__DETAIL__WEB = 'OPEN__DETAIL__WEB'
 export const CLOSE__DETAIL__WEB = 'CLOSE__DETAIL__WEB'

 export const OPEN__DETAIL__SOFTWARE = 'OPEN__DETAIL__SOFTWARE'
 export const CLOSE__DETAIL__SOFTWARE = 'CLOSE__DETAIL__SOFTWARE'

 export const OPEN__DETAIL__APP = 'OPEN__DETAIL__APP'
 export const CLOSE__DETAIL__APP = 'CLOSE__DETAIL__APP'

 export const OPEN__DETAIL__GAME = 'OPEN__DETAIL__GAME'
 export const CLOSE__DETAIL__GAME = 'CLOSE__DETAIL__GAME'

 export const OPEN__DETAIL__GRAPHIC = 'OPEN__DETAIL__GRAPHIC'
 export const CLOSE__DETAIL__GRAPHIC = 'CLOSE__DETAIL__GRAPHIC'

 export const OPEN__DETAIL__ANIMATION = 'OPEN__DETAIL__ANIMATION'
 export const CLOSE__DETAIL__ANIMATION = 'CLOSE__DETAIL__ANIMATION'

 export const OPEN__DETAIL__DIGITAL = 'OPEN__DETAIL__DIGITAL'
 export const CLOSE__DETAIL__DIGITAL = 'CLOSE__DETAIL__DIGITAL'
 
export const OPEN__DETAIL__BRANDING = 'OPEN__DETAIL__BRANDING'
 export const CLOSE__DETAIL__BRANDING = 'CLOSE__DETAIL__BRANDING'

export const OPEN__DETAIL__SEO = 'OPEN__DETAIL__SEO'
 export const CLOSE__DETAIL__SEO = 'CLOSE__DETAIL__SEO'

 export const OPEN__DETAIL__SMM = 'OPEN__DETAIL__SMM'
 export const CLOSE__DETAIL__SMM = 'CLOSE__DETAIL__SMM'

 export const OPEN__DETAIL__SMS = 'OPEN__DETAIL__SMS'
 export const CLOSE__DETAIL__SMS = 'CLOSE__DETAIL__SMS'

 export const OPEN__DETAIL__EMAIL = 'OPEN__DETAIL__EMAIL'
 export const CLOSE__DETAIL__EMAIL = 'CLOSE__DETAIL__EMAIL'

 export const OPEN__DETAIL__INFLUENCER = 'OPEN__DETAIL__INFLUENCER'
 export const CLOSE__DETAIL__INFLUENCER = 'CLOSE__DETAIL__INFLUENCER'

 export const OPEN__DETAIL__DOMAIN = 'OPEN__DETAIL__DOMAIN'
 export const CLOSE__DETAIL__DOMAIN = 'CLOSE__DETAIL__DOMAIN'

 export const OPEN__DETAIL__HOSTING = 'OPEN__DETAIL__HOSTING'
 export const CLOSE__DETAIL__HOSTING = 'CLOSE__DETAIL__HOSTING'

 export const OPEN__DETAIL__CLOUD = 'OPEN__DETAIL__CLOUD'
 export const CLOSE__DETAIL__CLOUD = 'CLOSE__DETAIL__CLOUD'
 
export const OPEN__DETAIL__AI = 'OPEN__DETAIL__AI'
 export const CLOSE__DETAIL__AI = 'CLOSE__DETAIL__AI'

export const OPEN__DETAIL__ROBOTICS = 'OPEN__DETAIL__ROBOTICS'
export const CLOSE__DETAIL__ROBOTICS= 'CLOSE__DETAIL__ROBOTICS'


export const OPEN__DETAIL__BUSINESS = 'OPEN__DETAIL__BUSINESS'
export const CLOSE__DETAIL__BUSINESS = 'CLOSE__DETAIL__BUSINESS'

 export const OPEN__DETAIL__RESEARCH = 'OPEN__DETAIL__RESEARCH'
 export const CLOSE__DETAIL__RESEARCH = 'CLOSE__DETAIL__RESEARCH'

 export const OPEN__DETAIL__DATA = 'OPEN__DETAIL__DATA'
 export const CLOSE__DETAIL__DATA = 'CLOSE__DETAIL__DATA'


//  QUOTE FORMS
export const OPEN__COMMEN__QUOTE = 'OPEN__COMMEN__QUOTE'
export const CLOSE__COMMEN__QUOTE = 'CLOSE__COMMEN__QUOTE'

export const OPEN__WEB__QUOTE = 'OPEN__WEB__QUOTE'
export const CLOSE__WEB__QUOTE = 'CLOSE__WEB__QUOTE'

export const OPEN__APP__QUOTE = 'OPEN__APP__QUOTE'
export const CLOSE__APP__QUOTE = 'CLOSE__APP__QUOTE'

export const OPEN__SOFTWARE__QUOTE = 'OPEN__SOFTWARE__QUOTE'
export const CLOSE__SOFTWARE__QUOTE = 'CLOSE__SOFTWARE__QUOTE'

export const OPEN__BUSINESS__QUOTE = 'OPEN__BUSINESS__QUOTE'
export const CLOSE__BUSINESS__QUOTE = 'CLOSE__BUSINESS__QUOTE'

export const OPEN__DIGITAL__QUOTE = 'OPEN__DIGITAL__QUOTE'
export const CLOSE__DIGITAL__QUOTE = 'CLOSE__DIGITAL__QUOTE'

export const OPEN__BRANDING__QUOTE = 'OPEN__BRANDING__QUOTE'
export const CLOSE__BRANDING__QUOTE = 'CLOSE__BRANDING__QUOTE'

export const OPEN__SEO__QUOTE = 'OPEN__SEO__QUOTE'
export const CLOSE__SEO__QUOTE = 'CLOSE__SEO__QUOTE'

export const OPEN__SMM__QUOTE = 'OPEN__SMM__QUOTE'
export const CLOSE__SMM__QUOTE = 'CLOSE__SMM__QUOTE'

export const OPEN__SMS__QUOTE = 'OPEN__SMS__QUOTE'
export const CLOSE__SMS__QUOTE = 'CLOSE__SMS__QUOTE'

export const OPEN__EMAIL__QUOTE = 'OPEN__EMAIL__QUOTE'
export const CLOSE__EMAIL__QUOTE = 'CLOSE__EMAIL__QUOTE'

export const OPEN__INFLUENCER__QUOTE = 'OPEN__INFLUENCER__QUOTE'
export const CLOSE__INFLUENCER__QUOTE = 'CLOSE__INFLUENCER__QUOTE'

export const OPEN__DOMAIN__QUOTE = 'OPEN__DOMAIN__QUOTE'
export const CLOSE__DOMAIN__QUOTE = 'CLOSE__DOMAIN__QUOTE'

export const OPEN__HOSTING__QUOTE = 'OPEN__HOSTING__QUOTE'
export const CLOSE__HOSTING__QUOTE = 'CLOSE__HOSTING__QUOTE'

export const OPEN__ANIMATION__QUOTE = 'OPEN__ANIMATION__QUOTE'
export const CLOSE__ANIMATION__QUOTE = 'CLOSE__ANIMATION__QUOTE'

export const OPEN__AI__QUOTE = 'OPEN__AI__QUOTE'
export const CLOSE__AI__QUOTE = 'CLOSE__AI__QUOTE'

export const OPEN__GAME__QUOTE = 'OPEN__GAME__QUOTE'
export const CLOSE__GAME__QUOTE = 'CLOSE__GAME__QUOTE'

export const OPEN__CLOUD__QUOTE = 'OPEN__CLOUD__QUOTE'
export const CLOSE__CLOUD__QUOTE = 'CLOSE__CLOUD__QUOTE'

export const OPEN__ROBOTICS__QUOTE = 'OPEN__ROBOTICS__QUOTE'
export const CLOSE__ROBOTICS__QUOTE = 'CLOSE__ROBOTICS__QUOTE'

export const OPEN__RESEARCH__QUOTE = 'OPEN__RESEARCH__QUOTE'
export const CLOSE__RESEARCH__QUOTE = 'CLOSE__RESEARCH__QUOTE'

export const OPEN__GRAPHIC__QUOTE = 'OPEN__GRAPHIC__QUOTE'
export const CLOSE__GRAPHIC__QUOTE = 'CLOSE__GRAPHIC__QUOTE'

export const OPEN__DATA__QUOTE = 'OPEN__DATA__QUOTE'
export const CLOSE__DATA__QUOTE = 'CLOSE__DATA__QUOTE'

export const SUCCESS__ALERT = 'SUCCESS__ALERT'
export const CLOSE__SUCCESS__ALERT = 'CLOSE__SUCCESS__ALERT'





// ADMIN PANEL
export const USER__IN = 'USER__IN'
export const USER__OUT = 'USER__OUT'

export const SUPER__ADMIN = 'SUPER__ADMIN'
export const SUPER__ADMIN__NULL = 'SUPER__ADMIN__NULL'


export const ADD__FORM__ID = ' ADD__FORM__ID'

export const FETCH__ID = 'FETCH__ID'

export const FETCH__BLOG__ID = 'FETCH__BLOG__Id'
